name: gh-integration PW

on:
  push:
  workflow_dispatch:
    inputs:
      TEST_BROWSER:
        description: "Browser for tests"
        required: true
        default: chrome
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false
      QA_ENV:
        type: choice
        description: 'QA Environment'
        required: false
        options:
          - sdet1
          - sdet2
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
        default: 'sdet1'

env:
    ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
    ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
    ALLURE_PROJECT_ID: 7806
    ALLURE_RESULTS: "allure-results"
    ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID || ''}}
    
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
     # - name: Install PW 
     #   run: npm init playwright@latest
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 7806
      - name: run playwright test
        run: |
            echo "chtonibud tam"
            cat ${ALLURE_TESTPLAN_PATH}
            allurectl watch -- npx playwright test
            echo "tam chtonibud posle"
            cat /home/runner/work/PW-test/PW-test/.allure/testplan.json
        env:
          TEST_ENDPOINT: ${{ github.event.inputs.TEST_ENDPOINT }}
          TEST_BROWSER: ${{ github.event.inputs.TEST_BROWSER }}
      - name: Get ALLURE_ environments
        run: |
              export $(allurectl job-run env)
              printenv | grep ALLURE_
              echo ${ALLURE_JOB_RUN_ID}
      - name: Get GITHUB_ environments
        run: | 
              printenv | grep GITHUB_
      - name: List results
        run: ls -la ${ALLURE_RESULTS}

  
