name: gh-integration

on:
  push:
  workflow_dispatch:
    inputs:
      TEST_ENDPOINT:
        description: "Endpoint for tests"
        required: true
        default: https://dev.github.com
      TEST_BROWSER:
        description: "Browser for tests"
        required: true
        default: chrome
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
    ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
    ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
    ALLURE_PROJECT_ID: 7806
    ALLURE_RESULTS: "allure-results"
    ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
    
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Install PW 
        run: npm init playwright@latest
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 7806
      - name: run playwright test
        run: |
            allurectl watch -- npx playwright test
        env:
          TEST_ENDPOINT: ${{ github.event.inputs.TEST_ENDPOINT }}
          TEST_BROWSER: ${{ github.event.inputs.TEST_BROWSER }}
      - name: Get ALLURE_ environments
        run: |
              export $(allurectl job-run env)
              printenv | grep ALLURE_
              echo ${ALLURE_JOB_RUN_ID}
      - name: Get GITHUB_ environments
        run: | 
              printenv | grep GITHUB_
      - name: List results
        run: ls -la ${ALLURE_RESULTS}

        #printenv grep ALLURE_ 
        #            export $(allurectl job-run env) 
        #- name: ========================= ls -la /home/runner/work/PW-test/PW-test/
        #run: ls -la /home/runner/work/PW-test/PW-test
